### PR TITLE
[REFACTOR]Bio API and Insee API calls

### PR DESCRIPTION
**Pull request by HAEKADI**
This PR introduces a new `fetch_all` method to the `APIClient` class, enabling efficient retrieval of paginated data from API endpoints. This addition significantly enhances the client's capabilities for handling large datasets that span multiple pages.

This method is used to refactor the INSEEAPIClient as well as BIOAPIClient.

### CODE REVIEW

**Review by XavierJp — CHANGES_REQUESTED** [review]

**Comment by HAEKADI** [comment]
@XavierJp Does this seem like a good enough separation, or do you think that data extraction from response should also be handled in a different method?

**Review by XavierJp — APPROVED** [review]
Much better

Naming could be improved a bit more : 

`pagination_handler` maybe `response_handler` ?

**Comment by HAEKADI** [comment]
I used `insee_pagination_handler` first and then changed it as in Python the better practice is to start the method name with a verb.

**Comment by HAEKADI** [comment]
`process_response_and_pagination` ?

**Comment by XavierJp** [comment]
Seems great

**Pull request merged**
